### ISSUE TITLE
Endless loop in package.json

### ISSUE THREAD

**Issue by screendriver** [esbenp/prettier-vscode#42] opened 2017-02-23 07:33 UTC
I enabled `editor.formatOnSave` and every time I open my `package.json` it tries to format it (`prettier` does not support formatting JSON files), then it saves, reformat, save, reformat... automatically. I don't get out of this loop.

![feb-23-2017 08-32-06](https://cloud.githubusercontent.com/assets/149248/23249031/a328eb50-f9a2-11e6-8069-5189358a71cc.gif)

**Comment by CiGit** [comment] 2017-02-23 08:54
Could not reproduce it with these steps. This extension runs only on javascript and javascriptreact. We'll need some more information.
* Extension version?
* Vscode version?
* OS?
* What language mode is selected for your `package.json` (bottom right of the editor)?

**Comment by CiGit** [comment] 2017-02-23 08:58
It may be an extension conflict. To find out, it will take some time if you have a lot of enabled extensions.

**Comment by screendriver** [comment] 2017-02-23 09:03
- Extension version 0.9.0
- VSCode version 1.9.1
- mac OS sierra
- `package.json` language is JSON

Ah I believe I found it out. I also installed [Add New Line to Files](https://marketplace.visualstudio.com/items?itemName=jdforsythe.add-new-line-to-files) to ensure that there is always a new line at the end of the file. If I disable it it works.

It seems that there is a conflict between your plugin and the other one 🤔

**Comment by CiGit** [comment] 2017-02-23 09:13
Thank you, that was fast. I'll try both plugins.

**Comment by CiGit** [comment] 2017-02-23 09:30
I've reproduced the problem with prettier disabled and `Add New Line to Files` enabled.
So the conflict with this extension can be eliminated. But it doesn't occur without formatOnSave. There is an embed formatter for JSON tho.

`FormatOnSave` is in Code since September 2016. `Add New Line to Files`'s last release is in June 2016. I think it needs to be updated.

**Comment by screendriver** [comment] 2017-02-23 09:32
So the solution would be to open an issue there?

**Comment by CiGit** [comment] 2017-02-23 09:38
I think it's the best idea. We can safely assume that the issue is not with this extension.
BTW the embed formatter removes last empty line for JSON.

**Comment by esbenp** [comment] 2017-02-23 09:40
@CiGit I have added you as collaborator - feel free to take any action you feel appropriate :-)

**Comment by screendriver** [comment] 2017-02-23 09:41
I opened an issue there https://github.com/jdforsythe/vscode-add-new-line-to-files/issues/1

**Comment by CiGit** [comment] 2017-02-23 09:49
@esbenp Thank you. With great power ...

@screendriver It's not a conflict with this one. It does exactly the same if you disable prettier.

**Comment by screendriver** [comment] 2017-02-23 12:45
Just a little update: I installed another plugin called [final-newline](https://marketplace.visualstudio.com/items?itemName=samverschueren.final-newline). With this one it seems to work together with `prettier-vscode`j

**Comment by CiGit** [comment] 2017-02-23 13:30
Great. Problem solved on this side. Closing

**Closed by CiGit** 2017-02-23 13:30 UTC

**Comment by screendriver** [comment] 2017-02-23 15:00
Yepp 😎 

Thank you for your quick help!
