### ISSUE TITLE
Modifying settings.json causes an error

### ISSUE THREAD

**Issue by stv8** [esbenp/prettier-vscode#171] opened 2017-07-18 16:24 UTC
Whenever I modify my `settings.json` file, I receive this error.

```
(json-to-ast) Cannot tokenize symbol </> at (/Users/svillars/Library/Application Support/Code/User/settings.json:1:1)
> 1 | // Place your settings in this file to overwrite the default settings
    | ^
  2 | {
  3 |     "vim.insertModeKeyBindings": [
  4 |         {
```

Disabling this extension makes it go away. 

vscode Version 1.14.1 (1.14.1)
macOS 10.11.6 (15G1421)

**Comment by CiGit** [comment] 2017-07-18 16:34
Duplicate of #149 
Comments are not part of JSON spec. The parser currently used is strict with that 😢

**Closed** 2017-07-18 16:34 UTC
Labels: duplicate
