### ISSUE TITLE
"Format Selection" formats whole document

### ISSUE THREAD

**Issue by OliverJAsh** [esbenp/prettier-vscode#134] opened 2017-06-22 17:08 UTC
Given:

``` js
const obj = {
  foo: 1,
  bar: 2,
};

const Foo = (x) => (
  x
);

```

If I select the object, or an entry within…

![image](https://user-images.githubusercontent.com/921609/27446540-eb6941f6-574b-11e7-860e-9d03717b17dc.png)

…and then run the "Format Selection" command, the whole document is then formatted instead of just the selection, resulting in:

``` js
const obj = {
  foo: 1,
  bar: 2
};

const Foo = x => x;
```

**Comment by CiGit** [comment] 2017-06-22 17:13
It seems to me it formats the whole node which contains the selection.
So ti should format `obj` but not `Foo`
@josephfrazier should be able to tell us a little more about that :-)

**Comment by brunolemos** [comment] 2017-06-24 03:15
I've been facing this for around two weeks or more. Maybe caused by #113?

**Comment by brunolemos** [comment] 2017-06-24 03:27
From [v0.18.0](https://github.com/esbenp/prettier-vscode/releases/tag/v0.18.0) release:

> Improved range formater
@josephfrazier brought his work on prettier's range formater here. Our range formater is now improved working.
⚠️ With eslint's integration it will format the entire document. But it still is waaaaaaaay better than before !

Weird that it was an already known behaviour and still released 🤔

**Comment by OliverJAsh** [comment] 2017-06-24 03:34
> I work on projects that haven't applied prettier on whole source code, but as I try to apply on my new code it reformats the whole document and make giant git diffs.

Same here.

**Comment by brunolemos** [comment] 2017-06-24 03:39
### `"prettier.eslintIntegration": true`:
Formats the whole document instead of the selection.

![ep1](https://user-images.githubusercontent.com/619186/27505408-5aee85de-5875-11e7-916f-95d1a742e343.gif)

### `"prettier.eslintIntegration": false`:
Formats the selection correctly if the selection is not at the beginning of the document

![ep2](https://user-images.githubusercontent.com/619186/27505407-5aed944e-5875-11e7-8e47-7b331af4f204.gif)

Formats the whole document if the selection is not at the beginning of the document

![ep3](https://user-images.githubusercontent.com/619186/27505409-5af2a51a-5875-11e7-8220-bb7401d523d3.gif)

**Comment by CiGit** [comment] 2017-06-24 07:47
Thanks for the more detailed analysis.

The fact that it formats the entire document is a known issue (I forgot to open). Globally I found #113 to be better than what we had before. The entire range formater was buggy. You had to select a valid `Program` to avoid ParseError.

**Comment by josephfrazier** [comment] 2017-06-24 16:27
From https://github.com/esbenp/prettier-vscode/issues/134#issuecomment-310444168:

> It seems to me it formats the whole node which contains the selection.
> So it should format `obj` but not `Foo`
> @josephfrazier should be able to tell us a little more about that :-)

Yes, prettier has to walk up the AST until it finds a formattable node, which in practice means one that could be a standalone Program. See https://github.com/prettier/prettier/pull/1659#issuecomment-303167383 for more details.

**Comment by CiGit** [comment] 2017-06-27 21:53
Fixed with latest release.

**Closed by CiGit** 2017-06-27 21:53 UTC
Labels: bug, dependency

**Comment by brunolemos** [comment] 2017-07-18 23:36
Nothing changed for me, still have the bug on v0.21.0.
@OliverJAsh Does it work for you?

cc @CiGit

**Comment by CiGit** [comment] 2017-07-19 06:00
@brunolemos This is known #137 
The question currently is what to do with that case.

**Comment by cyborkonline** [comment] 2018-02-28 23:37
Still having this issue...

**Comment by danielalmeidagoncalves** [comment] 2018-03-08 09:47
Same here with version 1.2.2

**Comment by RobinMalfait** [comment] 2018-03-08 11:11
I know this is still a problem, but I am actually wondering why this is a use case?

Do people only use prettier on specific parts of the code? If so, why?

**Comment by georgecrawford** [comment] 2018-03-21 17:01
We haven't yet migrated to prettier wholesale. However, I personally love it, and use it to format blocks of untidy code (especially when pasting from elsewhere), which I then tweak slightly to match our house style. I can't format the whole file, as the resulting diff would be too noisy.

**Comment by danielalmeidagoncalves** [comment] 2018-03-21 22:05
I have a similar approach of @georgecrawford. I kind of use the prettier as a first formatter and adapt some minor tweaks to our team code style. If I format all the file, my teammate wouldn't be very happy with the diffs on the code reviews ;)

**Comment by sppatel** [comment] 2018-03-28 12:05
Agree this is needed - selectively formatting parts of your code during transition periods is a common use case.

**Comment by psy901** [comment] 2018-05-02 08:51
Agreed. When I edit some parts of the existing code and try to format the edited part, it formats the whole document, which leads to unnecessary changes in git.

**Comment by rattrayalex-stripe** [comment] 2018-08-27 18:29
@CiGit should this be reopened?

@josephfrazier has experience shown that this feature can work well with prettier?

**Comment by CiGit** [comment] 2018-08-27 19:15
The extension calls prettier's range formatter. This is enabled for a hardcoded list of language ids (Those I know support this feature).
here: https://github.com/prettier/prettier-vscode/blob/v1.6.1/src/utils.ts#L42-L51

For the case with eslint see #137 

If there is something else, please open a new issue 😉

**Comment by vk011** [comment] 2020-01-30 10:26
This is still an issue, and the eslint config option is not supported ?

**Comment by devinrhode2** [comment] 2020-03-19 20:46
I believe I am also seeing this issue. Sad thing my company doesn't use prettier, but the worse thing is this "Format selection" formatting outside of my selection.
